### ISSUE TITLE
SSH Keys are mandatory - but should be optional

### ISSUE THREAD

**Issue by Intelopment** [metmajer/Dynatrace-CDDemo-DeployTool#1]
When running a build, i got an error because I had never generated SSH keys. I don't need them, but the build crashed without they keys.
Log contents:

Debian-7-amd64-vmware: Provisioning with Ansible...
    Debian-7-amd64-vmware: Uploading Playbook directory to Ansible staging directory...
    Debian-7-amd64-vmware: Creating directory: /var/ansible-local
    Debian-7-amd64-vmware: Uploading main Playbook file...
    Debian-7-amd64-vmware: Uploading inventory file...
    Debian-7-amd64-vmware: Executing Ansible: cd /var/ansible-local && . ./set-install-env.sh && ansible-playbook -e 'ansible_role=easytravel-cd-debian' /var/ansible-local/playbook.yml -c local -i /var/ansible-local/packer-provisioner-ansible-local738369559
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: PLAY [all] ********************************************************************
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: GATHERING FACTS ***************************************************************
    Debian-7-amd64-vmware: ok: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | apt update_cache=yes upgrade=dist] ***********************
    Debian-7-amd64-vmware: changed: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Install package 'locales'] *******************************
    Debian-7-amd64-vmware: ok: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Generate locales] ****************************************
    Debian-7-amd64-vmware: ok: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Update locales] ******************************************
    Debian-7-amd64-vmware: changed: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Install a (2s) delay to 'interface up' to make dhclient happy] ***
    Debian-7-amd64-vmware: changed: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Create group 'deploy'] ***********************************
    Debian-7-amd64-vmware: ok: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Create user 'deploy' in group 'deploy'] ******************
    Debian-7-amd64-vmware: ok: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Set password for user 'deploy'] **************************
    Debian-7-amd64-vmware: changed: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Add user 'deploy' to sudoers] ****************************
    Debian-7-amd64-vmware: changed: [127.0.0.1]
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: TASK: [base-debian | Add SSH public key to user 'deploy'] *********************
    Debian-7-amd64-vmware: fatal: [127.0.0.1] => could not locate file in lookup: keys/dynatrace.pub
    Debian-7-amd64-vmware: 
    Debian-7-amd64-vmware: FATAL: all hosts have already failed -- aborting
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: PLAY RECAP ********************************************************************
    Debian-7-amd64-vmware: to retry, use: --limit @/home/deploy/playbook.retry
    Debian-7-amd64-vmware:
    Debian-7-amd64-vmware: 127.0.0.1                  : ok=10   changed=5    unreachable=1    failed=0
    Debian-7-amd64-vmware:
==> Debian-7-amd64-vmware: Stopping virtual machine...
==> Debian-7-amd64-vmware: Deleting output directory...
Build 'Debian-7-amd64-vmware' errored: Error executing Ansible: Non-zero exit status: 3

==> Some builds didn't complete successfully and had errors:
--> Debian-7-amd64-vmware: Error executing Ansible: Non-zero exit status: 3

==> Builds finished but no artifacts were created.

**Comment by metmajer** [comment]
Fixed by pull request #3.
