### ISSUE TITLE
SSH Key generation fails due to lack of directory

### ISSUE THREAD

**Issue by Intelopment** [metmajer/Dynatrace-CDDemo-DeployTool#2]
When generating SSH keys, it fails due to the lack of a specified directory.
The command:
./bin/create-ssh-keypair.sh deploy
fails due to the following error:
SEA123634MACN01:Dynatrace-CDDemo-DeployTool-master jhoffman$ ./bin/create-ssh-keypair.sh deploy
open keys/deploy failed: No such file or directory.
Saving the key failed: keys/deploy.
./bin/create-ssh-keypair.sh: line 9: keys/deploy.password: No such file or directory
chmod: keys/deploy*: No such file or directory
mv: rename keys/deploy.pub to ansible/keys/deploy.pub: No such file or directory
SEA123634MACN01:Dynatrace-CDDemo-DeployTool-master jhoffman$ 

The command expects any directories specified in the -f to preexist.  Once I created keys/ it worked fine.

**Comment by metmajer** [comment]
Fixed by pull request #3.
